extends:
  - 'typescript-shareable'

parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 'latest'

env:
  browser: true
  es6: true
  # node: true

ignorePatterns:
  - 'tsup.config.ts'

rules:
  '@typescript-eslint/explicit-function-return-type':
    - error
  '@typescript-eslint/no-floating-promises': off # temporary disable the rule as until false positive is fixed
  '@typescript-eslint/no-misused-promises': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/strict-boolean-expressions': off
  'functional/no-method-signature': off
  'import/order':
    - 'error'
    - groups:
        - external
        - internal
      pathGroupsExcludedImportTypes:
        - builtin
      newlines-between: always
  'import/no-cycle':
    - 'error'
    - maxDepth: 5
