# Run linting, unit tests, check build is possible. Standard requirements
# that should always be green. Tested on NodeJS LTS and current stable.

name: CI

on:
  push:
  pull_request:
    branches: main

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: ['18']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commit message
        if: ${{ github.event_name == 'pull_request' }}
        run: sbin/commitlint.py ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Build docs
        run: yarn run build:docs

      - name: Check that no new files to be committed
        run: git diff --exit-code

      # TODO: Add code coverage in GitHub

      - name: Linting
        run: yarn lint # check code formatting

      - name: Unit testing
        run: yarn test # run unit tests
